### ISSUE TITLE
基于raphael 会不会更简单一些。

### ISSUE THREAD

**Issue by giscafer** [zhangyuanliang/flow-chart#29]
图形绘制使用[DmitryBaranovskiy/raphael](https://github.com/DmitryBaranovskiy/raphael)

**Comment by zhangyuanliang** [comment]
对raphael了解太少，不过我刚看了一下它的官网Demo太少，远不及d3js强大，而且raphael最后一次发布版本是2016年，issues更是无人维护...如果是做项目感觉谨慎点比较好。

**Comment by giscafer** [comment]
这个了解一下。Raphael https://github.com/giscafer/LarryleWorkFlow

**Comment by zhangyuanliang** [comment]
不错，有空学习一下

**Comment by giscafer** [comment]
基于 `G6` 或许更好
