### ISSUE TITLE
大神，我想参照您的代码做二次开发，但是无奈水平太低，可否给个QQ，咨询相关技术问题？

### ISSUE THREAD

**Issue by hacker0817** [zhangyuanliang/flow-chart#31]
大神，我想参照您的代码做二次开发，但是无奈水平太低，可否给个QQ，咨询相关技术问题？

**Comment by zhangyuanliang** [comment]
805013595 你都需要哪些功能？如果只是流程图绘制，建议你跟一下我重构的项目 [flowchart-vue](https://github.com/zhangyuanliang/flowchart-vue)
